config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {registrations: 'registrations', sessions: 'sessions'}
  root to: 'pages#home'

  filter :locale

  get 'home'          => 'pages#home', as: :home
  get 'contact'       => 'pages#contact', as: :contact
  get 'about'         => 'pages#about', as: :about

  resource :dashboard,      only: [:show]
  resources :insurances, except: [:destroy, :edit, :update] do
    collection do
      get 'bought'
    end
  end
  resources :vehicles, except: [:destroy, :edit, :update, :new] do
    collection do
      match 'search', via: [:get, :post]
    end
  end


  ##
  # API Routes
  ##

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :insurances, except: [:new, :edit, :update]
      resources :rates, except: [:new, :edit]
      resources :vehicles, except: [:new, :edit]
      resources :users, except: [:new, :edit]
    end
  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  # Constants
  CATEGORIES = ["CAMPEROS Y CAMIONETAS", "BUSES Y BUSETAS DE SERVICIO PUBLICO URBANO", "MOTOS", "AUTOS DE NEGOCIOS Y TAXIS", "AUTOS FAMILIARES", "VEHICULO PARA SEIS O MAS PASAJEROS", "CARGA O MIXTO", "SERVICIO PUBLICO INTERMUNICIPAL", "OFICIALES ESPECIALES"]
  SUBCATEGORIES = ["Más de 15 toneladas", "1500 a 2500 cc", "De 5 a 15 toneladas", "MOTOCARROS", "Menos de 5 toneladas", "2500 cc o mas", "De 100 a 200 cc", "", "Menos de 2500 cc", "Más de 200 cc", "Más de 2500 cc", "Menos de 1500 cc", "10 ó mas pasajeros", "Menos de 100 cc", "Menor de 10 pasajeros"]
  SUBCATEGORIES_HASH = { "CAMPEROS Y CAMIONETAS" => ["Menos de 1500 cc", "1500 a 2500 cc", "Más de 2500 cc"],
    "BUSES Y BUSETAS DE SERVICIO PUBLICO URBANO"=>[""],
    "MOTOS"=>["Menos de 100 cc", "De 100 a 200 cc", "Más de 200 cc", "MOTOCARROS"],
    "AUTOS DE NEGOCIOS Y TAXIS"=>["Menos de 1500 cc", "1500 a 2500 cc", "Más de 2500 cc"],
    "AUTOS FAMILIARES"=>["Menos de 1500 cc", "1500 a 2500 cc", "Más de 2500 cc"],
    "VEHICULO PARA SEIS O MAS PASAJEROS"=>["Menos de 2500 cc", "2500 cc o mas"],
    "CARGA O MIXTO"=>["Menos de 5 toneladas", "De 5 a 15 toneladas", "Más de 15 toneladas"],
    "SERVICIO PUBLICO INTERMUNICIPAL"=>["Menor de 10 pasajeros", "10 ó mas pasajeros"],
    "OFICIALES ESPECIALES"=>["Menos de 1500 cc", "1500 a 2500 cc", "Más de 2500 cc"]}

  VALUE_TYPES = ["Pasajeros", "Cilindraje", "Toneladas", ""]
  VALUE_TYPES_HASH = { "CAMPEROS Y CAMIONETAS" => "Cilindraje",
    "BUSES Y BUSETAS DE SERVICIO PUBLICO URBANO"=>"",
    "MOTOS"=>"Cilindraje",
    "AUTOS DE NEGOCIOS Y TAXIS"=>"Cilindraje",
    "AUTOS FAMILIARES"=>"Cilindraje",
    "VEHICULO PARA SEIS O MAS PASAJEROS"=>"Cilindraje",
    "CARGA O MIXTO"=>"Toneladas",
    "SERVICIO PUBLICO INTERMUNICIPAL"=>"Pasajeros",
    "OFICIALES ESPECIALES"=>"Cilindraje"}

  # Associations
  belongs_to :user
  belongs_to :rate
  has_many :insurances

  # Validations
  # Acording to Colombia types of licenses found on: http://andina.com.co/blog/sabes-cuantos-tipos-de-placas-existen-en-colombia/
  # Un comment format validator if only colombian licenses
  validates :license, presence: true#, format: {with: /[A-Z]{1,3}\d{3,4}/}, length: { minimum: 5, maximum: 6}
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  validates :subcategory, presence: false, inclusion: { in: SUBCATEGORIES }
  validates :age, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :value_type, presence: false, inclusion: { in: VALUE_TYPES }
  validates :value, presence: false, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # Hooks
  before_save :upcase_license
  before_save :set_rate
  before_save :set_value_type

  # Methods
  def upcase_license
    license.upcase!
  end

  def next_insurance_start
    return DateTime.now if insurances.empty?
    insurances.first.ends_at + 1.day
  end

  def set_rate
    self.rate_id = Rate.select(:id).where(category: category, subcategory: subcategory).where("max_age >= ? and min_age <=  ?", age, age).first.id
  end

  def set_value_type
    self.value_type = VALUE_TYPES_HASH[category]
  end

  def full_value
    "#{value} #{value_type}"
  end

  def insuranced?
    insurances.any? && insurances.first.ends_at > DateTime.now
  end
end

app/controllers/api/v1/vehicles_controller.rb
class Api::V1::VehiclesController < Api::BaseController

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      render status: 201, template: 'api/v1/vehicles/show'
    else
      render status: 400, json: @vehicle.errors.messages.to_json
    end
  end

  def index
    @vehicles = Vehicle.all
  end

  def show
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.update(params[:id], vehicle_params)
    render status: 200, template: 'api/v1/vehicles/show'
  end

  def destroy
    @vehicle = Vehicle.find(params[:id]).destroy
    render status: 200, template: 'api/v1/vehicles/show'
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:license, :category, :subcategory, :age, :value, :value_type, :user_id)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_values, only: [:search, :create]

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user_id = current_user.id
    if @vehicle.save
      @rate = @vehicle.rate
      flash[:success] = "Vehiculo registrado"
    else
      flash[:danger] = "No se pudo registrar"
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  def index
    authorize Vehicle
    @vehicles = Vehicle.includes(:user).includes(:rate).paginate(page: params[:page])
  end

  def show
    @vehicle = Vehicle.includes(:rate).includes(:user).find(params[:id])
    authorize @vehicle
    @user = @vehicle.user
    @rate = @vehicle.rate
  end

  def search
    byebug
    query = Vehicle.where(search_params)
    query = query.where(user_id: current_user.id) unless current_user.admin?
    @vehicle = query.includes(:insurances).first
    unless @vehicle.nil?
      authorize @vehicle
      @rate = @vehicle.rate
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  protected

  def vehicle_params
    params.require(:vehicle).permit(:license, :category, :subcategory, :age, :value, :value_type)
  end

  def search_params
    search_params = params.require(:vehicle).permit(:license)
    search_params.each{|k,v| params[k] = v.upcase! }
  end

  def load_values
    @category = Vehicle::CATEGORIES.first
    @subcategories = Vehicle::SUBCATEGORIES_HASH[@category]
    @value_type = Vehicle::VALUE_TYPES_HASH[@category]
  end
end

app/views/vehicles/_enable_insurance_form.js.erb
// Insurance form
$('#insurance_vehicle_id').val("<%= @vehicle.id %>");
$('#insurance_license_label').html("Placa: <%= @vehicle.license %>");
$('#insurance_fosyga_label').html("<%= price(@rate.fosyga) %>");
$('#insurance_bonus_label').html("<%= price(@rate.bonus) %>");
$('#insurance_total_label').html("<%= price(@rate.total) %>");
$('#new_insurance_submit').prop('disabled', false);
found_message = $('#insurance_state_message');
insurance_message = $('#insurance_end_message');
insurance_section = $('#insurance_section');
insurance_section.show();

<% if @vehicle.insurances.any? %>
  <% insurance = @vehicle.insurances.first %>
  found_message.html("<%= I18n.t('insurances.new.insurance_found') %>"+"<%= insurance.ends_at.strftime('%d %b %Y') %>");
  ends_date = "<%= (insurance.ends_at + 1.day).strftime('%d %b %Y') %>"
<% else %>
  found_message.html("<%= I18n.t('insurances.new.insurance_not_found') %>");
  ends_date = "<%= (DateTime.now).strftime('%d %b %Y') %>"
<% end %>
insurance_message.html("<%= I18n.t('insurances.new.insurance_end_message') %>"+ends_date);

app/views/vehicles/_new_form.html.haml
= simple_form_for(@vehicle, url: vehicles_path, remote: true, html: { method: :post, id: 'new_vehicle' }) do |f|
  = render 'shared/error_messages', object: f.object
  = f.input :license, as: :hidden, input_html: {id: 'vehicle_license_hidden'}
  = f.input :category, collection: Vehicle::CATEGORIES, include_blank: false, selected: @category, input_html: { onChange: 'set_options_by_category(event)' }
  = f.input :subcategory, collection: @subcategories, include_blank: false
  = f.input :age, hint: t('vehicles.new.age_hint'), as: :integer, input_html: { min: '0', step: 'any' }
  = f.input :value_type, as: :hidden, value: (@vehicle.value_type || @value_type)
  = f.input :value, as: :integer, input_html: { min: '0', step: 'any' }, label: @value_type
  = f.button :submit, t('vehicles.new.submit'), class: "btn btn-primary"

app/views/vehicles/_search_form.html.haml
/ form id = new_vehicle
= simple_form_for(@vehicle, url: search_vehicles_path, remote: true, html: { method: :post, id: 'search_vehicle_form' }) do |f|
  = f.input :license, required: true, autofocus: true, input_html: { onChange: "search_vehicle_by_license(event)" }

app/views/vehicles/_vehicle.html.haml
%tr
  %td
    = link_to vehicle.license, vehicle_path(vehicle)
  %td= vehicle.rate.code
  %td= vehicle.category
  %td= vehicle.subcategory
  %td= vehicle.age
  %td= vehicle.full_value
  %td= vehicle.user.full_name

app/views/vehicles/create.js.erb
<% flash.each do |type, msg| %>
  $('#alerts').html($('#alerts').html() + "<div class='alert alert-<%= type %>' role='alert'><%= msg %></div>");
  $('#new_vehicle_form_container').html("<%= j render partial: 'vehicles/new_form' %>");
<% end %>
<% if @vehicle.persisted? %>
  $("#vehicle_section").hide();
  <%= render partial: 'vehicles/enable_insurance_form' %>
<% end %>

app/views/vehicles/index.html.haml
- provide(:title, t('vehicles.index.title'))

%h1.page-header= t('vehicles.index.header')
.row
  .col-xs-12
    = will_paginate @vehicles

    %table.table.table-striped.table-hover.table-condensed
      %thead
        %th Placa
        %th Codigo
        %th Categoria
        %th Subcategoria
        %th Edad
        %th Cilindraje/Pasajeros/Toneladas
        %th Nombre
      %tbody
        = render @vehicles

    = will_paginate @vehicles

app/views/vehicles/search.js.erb
<% if @vehicle.nil? %>
  $('#alerts').html("");
  $('#new_vehicle input').each(function(index){
    $(this).prop('disabled', false);
  });
  $('#insurance_section').hide();
  $('#new_insurance_submit').prop('disabled', true);
<% else %>
  $('#alerts').html("<div class='alert alert-success' role='alert' style='margin-top: 30px'><%= I18n.t('vehicles.search.found') %></div>");

  // Vehicle form
  $('#new_vehicle_form_container').html("<%= j render partial: 'vehicles/new_form' %>");
  $('#new_vehicle input').each(function(index){
    $(this).prop('disabled', true);
  });
  $('#vehicle_license_hidden').val("<%= @vehicle.license %>");

  // Insurance form
  <%= render partial: 'vehicles/enable_insurance_form' %>
<% end %>

app/views/vehicles/show.html.haml
- provide(:title, @vehicle.license)

%h1.page-header= @vehicle.license
.row
  .col-xs-12
    %b Categoria:
    %p= @vehicle.category
    %b Subcategoria:
    %p= @vehicle.subcategory
    %b Edad:
    %p= @vehicle.age
    %b= "#{@vehicle.value_type}:"
    %p= @vehicle.value
    %h2.page-header.page-subheader Responsable
    %b Nombre Completo
    %p= @user.full_name
    %b= @user.document_type
    %p= @user.document
    %b Email
    %p= @user.email
    - if @user.phone.present?
      %b Telefono
      %p= @user.phone