config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {registrations: 'registrations', sessions: 'sessions'}
  root to: 'pages#home'

  filter :locale

  get 'home'          => 'pages#home', as: :home
  get 'contact'       => 'pages#contact', as: :contact
  get 'about'         => 'pages#about', as: :about

  resource :dashboard,      only: [:show]
  resources :insurances, except: [:destroy, :edit, :update] do
    collection do
      get 'bought'
    end
  end
  resources :vehicles, except: [:destroy, :edit, :update, :new] do
    collection do
      match 'search', via: [:get, :post]
    end
  end


  ##
  # API Routes
  ##

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :insurances, except: [:new, :edit, :update]
      resources :rates, except: [:new, :edit]
      resources :vehicles, except: [:new, :edit]
      resources :users, except: [:new, :edit]
    end
  end
end

app/views/layouts/_flash_messages.html.haml
#alerts
- flash.each do |type, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{type} fade in top"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{type}"

app/views/layouts/_headers.html.haml
%meta{ charset: 'utf-8' }
%meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
// To set title in the view use provide method
-# %title= full_title(yield(:title))
= csrf_meta_tags

app/views/layouts/_navbar.html.haml
// Navbar
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "#{root_path}"} SOAT
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to t('dashboard.navbar.buy'), new_insurance_path
        - unless current_user.admin?
          %li
            = link_to t('dashboard.navbar.insurances'), bought_insurances_path
        %li
          = link_to t('dashboard.navbar.profile'), edit_user_registration_path
        %li
          = link_to t('dashboard.navbar.logout'), destroy_user_session_path, method: :delete
      -# %form.navbar-form.navbar-right
      -#   %input.form-control{placeholder: "Search...", type: "text"}

app/views/layouts/_sidebar.html.haml
#sidebar
  %ul.nav.nav-sidebar
    %li{class: "#{@active == 'dashboard' ? 'active' : 'inactive'}"}
      = link_to t('dashboard.sidebar.dashboard'), dashboard_path
    - if current_user.admin?
      %li{class: "#{@active == 'sells' ? 'active' : 'inactive'}"}
        = link_to t('dashboard.sidebar.sell'), insurances_path
      %li{class: "#{@active == 'vehicles' ? 'active' : 'inactive'}"}
        = link_to t('dashboard.sidebar.vehicles'), vehicles_path
  %ul.nav.nav-sidebar
    %li{class: "#{@active == 'buy' ? 'active' : 'inactive'}"}
      = link_to t('dashboard.sidebar.buy'), new_insurance_path
    - unless current_user.admin?
      %li{class: "#{@active == 'bought' ? 'active' : 'inactive'}"}
        = link_to t('dashboard.sidebar.shopping'), bought_insurances_path
    %ul.nav.nav-sidebar
    %li{class: "#{@active == 'profile' ? 'active' : 'inactive'}"}
      = link_to t('dashboard.sidebar.profile'), edit_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render 'layouts/headers'

    = include_gon

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'cable', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'common', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'dashboard', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'static', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/navbar'
    #main_container.container-fluid
      .row
        .col-sm-3.col-md-2.sidebar
          = render 'layouts/sidebar'
        #main.col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
          = render 'layouts/flash_messages'
          = yield
          -# = render 'layouts/footer'